### PR TITLE
Release v0.9.8

### PR DESCRIPTION
**Pull request by hongquan**

### CODE REVIEW

**Comment by hfiguiere** [comment]
build fail because it access session and system bus. This is not allowed in general and you should determine withi dbus names you need to access.

**Comment by hfiguiere** [comment]
Also `        url: git://git.linuxtv.org/zbar.git`: https is prefered. If there is an actual reason you are not able to use https for git, an exception needs to be applied for.

BTW this package also build against an runtime that has been EOL for over a year.

GNOME 43 is the most recent and you should update to it. This would mean removing some of the dependencies like libhandy that are in the runtime.

**Comment by hfiguiere** [comment]
> build fail because it access session and system bus. This is not allowed in general and you should determine withi dbus names you need to access.

See https://github.com/flathub/flathub/issues/2785

**Comment by hongquan** [comment]
Thank you, @hfiguiere , I'm updating the Flatpak build. However, this time I get into an issue like this:
image
The HdyHeaderBar become big when running inside Flatpak. How to fix it?

**Comment by hfiguiere** [comment]
The runtime has libhandy 1.8.0 so it's probably where the difference lies in. Likely not flatpak specific, and likely to be encountered with distro packages.

It's ok to leave what you build if that works better. I was just indicating it was in the runtime.

**Comment by nedrichards** [comment]
For sure would love to see a newer runtime - this is my last app left with an older runtime!

**Comment by hongquan** [comment]
@nedrichards I already [upgrade](https://github.com/hongquan/CoBang/tree/feature/upgrade-flatpak-env) to v43 of the runtime at my local. But because of the issue with big header bar, I haven't released it yet.

**Comment by hongquan** [comment]
Close. Will release v0.9.9 instead.

**Pull request closed without merging**
